remote_theme: pages-themes/minimal@v0.2.0

title: Emílias - Armação em Bits
description: Emílias – Armação em Bits é um Programa de Extensão do 
Departamento Acadêmico de Informática (DAINF) da Universidade Tecnológica Federal do Paraná (UTFPR) - Câmpus Curitiba.
