remote_theme: pages-themes/minimal@v0.2.0

title: Emílias - Armação em Bits
description: Um Programa de Extensão do Departamento Acadêmico de Informática (DAINF) da Universidade Tecnológica Federal do Paraná (UTFPR) - Câmpus Curitiba.
logo: ./images/emilias-768x768.png
